"""add vk and tg verify

Revision ID: 405d48b268b7
Revises: e74d671272dc
Create Date: 2024-09-03 15:23:13.797621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405d48b268b7'
down_revision: Union[str, None] = 'e74d671272dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('tg_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###
