"""Add achievements

Revision ID: 498dfc69cd1e
Revises: 77cb9804e4d8
Create Date: 2024-08-16 19:40:42.994253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498dfc69cd1e'
down_revision: Union[str, None] = '77cb9804e4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('rate', sa.String(), nullable=True),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievements')
    # ### end Alembic commands ###
