version: "3"

services:
  vchern_api_service:
    build: .
    container_name: vchern_api_service
    volumes:
      - ./static:/code/static
    expose:
      - 8090
    depends_on:
      - vchern_api_db

  vchern_api_db:
    image: postgres:alpine
    container_name: vchern_api_db
    volumes:
      - postgres_data_vchern_api:/var/lib/postgresql/data/
    ports:
      - "10800:5432"
    env_file:
      - .env.db

  nginx_vchern_api:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx_conf.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - vchern_api_service

volumes:
  postgres_data_vchern_api: