"""add links for project

Revision ID: 0b49522b64c1
Revises: 1217f44eba54
Create Date: 2024-08-04 00:33:41.162782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b49522b64c1'
down_revision: Union[str, None] = '1217f44eba54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_link', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_link')
    op.drop_column('projects', 'github_link')
    # ### end Alembic commands ###
